import hre from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const [admin, staff1] = await hre.ethers.getSigners();

  console.log("Deploying LabRegistry with admin:", admin.address);

  const LabRegistry = await hre.ethers.getContractFactory("LabRegistry");
  const registry = await LabRegistry.deploy();
  await registry.waitForDeployment();

  const address = await registry.getAddress();
  console.log("LabRegistry deployed to:", address);

  // Grant staff role to second account
  await registry.addStaff(staff1.address);
  console.log("Added staff:", staff1.address);

  // Seed equipment (admin is also authorized as staff per contract modifier)
  await registry.addEquipment(1, "Oscilloscope");
  await registry.addEquipment(2, "Function Generator");
  await registry.addEquipment(3, "Digital Multimeter");
  console.log("Seeded 3 equipment items (IDs 1, 2, 3)");

  // ── Copy ABI + address into frontend ────────────────────────────────────
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/LabRegistry.sol/LabRegistry.json"
  );

  if (!fs.existsSync(artifactPath)) {
    console.error("Artifact not found. Run `npx hardhat compile` first.");
    process.exit(1);
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const frontendSrc = path.join(__dirname, "../frontend/src");
  if (!fs.existsSync(frontendSrc)) {
    fs.mkdirSync(frontendSrc, { recursive: true });
  }

  const abiContent = `// Auto-generated by scripts/deploy.js — do not edit manually.
// Re-run \`npm run deploy\` to refresh after a new deployment.

export const ABI = ${JSON.stringify(artifact.abi, null, 2)};

export const CONTRACT_ADDRESS = "${address}";
`;

  fs.writeFileSync(path.join(frontendSrc, "abi.js"), abiContent);
  console.log("ABI + address written to frontend/src/abi.js");

  // Save a human-readable deployment summary
  const summary = {
    contractAddress: address,
    admin: admin.address,
    staff: [staff1.address],
    equipment: [
      { id: 1, name: "Oscilloscope" },
      { id: 2, name: "Function Generator" },
      { id: 3, name: "Digital Multimeter" },
    ],
    deployedAt: new Date().toISOString(),
  };

  fs.writeFileSync(
    path.join(__dirname, "../deployment.json"),
    JSON.stringify(summary, null, 2)
  );
  console.log("Deployment summary saved to deployment.json");
  console.log("\n--- Hardhat test accounts ---");
  console.log("Admin  (Account #0):", admin.address);
  console.log("Staff  (Account #1):", staff1.address);
  console.log("(Import these into MetaMask using the Hardhat mnemonic)");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
